name: Run Script on Push

on:
  push:
    branches:
      - main
      - "**"   # triggers on push to any branch (optional)

jobs:
  run-script-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "Environment setup complete"

      - name: Make script executable (optional)
        run: chmod +x ./scripts/myscript.sh

      - name: Run the script
        run: ./scripts/myscript.sh
